Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
]

aboutUs/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'aboutUs'

urlpatterns = [
    path('', views.AboutUs, name='aboutUs'),
]

covid_count/urls.py
from django.urls import path
from . import views

app_name = 'covid_count'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.access_db_and_return_latest, name='add'),
    path('table/', views.table, name='table')
]

educovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
]

edukasi/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'edukasi'

urlpatterns = [
    path('', views.edukasi, name='edukasi'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('story1/', views.home2, name='home2'),
    path('story5/', views.home, name='home'),
    path('story5/cv/', views.cv, name='cv'),
]

screening_tests/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'screening_tests'

urlpatterns = [
    path('', views.test, name='test'),
    path('result/', views.result, name='res'),
]

urlpatterns += staticfiles_urlpatterns()

covid_count/models.py
from django.db import models
from django.core.validators import MinValueValidator
# Create your models here.
class COVIDStat(models.Model):
    date_accessed = models.DateTimeField()
    confirmed = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    deaths = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    recovered = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    active = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    
    # util method to check if no change has occurred
    # since last API access, instead of overriding
    # __eq__ which might mess up the database
    def change(other_entry, self):
        return {
           'confirmed': self.confirmed - other_entry.confirmed,
           'deaths': self.deaths - other_entry.deaths,
           'recovered': self.recovered - other_entry.recovered,
           'active': self.active - other_entry.active
           }

covid_count/views.py
from django.shortcuts import render
from django.http import JsonResponse
from datetime import datetime, timedelta, date, time
from django.forms.models import model_to_dict
from django.utils.timezone import make_aware
from .models import COVIDStat
import requests
import json
# Create your views here.

def index(request):
    context = json.loads(access_db_and_return_latest(request).content)
    return render(request, 'covid_count/index.html', context)

def table(request):
    context = {'database' : COVIDStat.objects.all()}
    return render(request, 'covid_count/table.html', context)

def access_db_and_return_latest(request):
    access_date = make_aware(datetime.now().replace(microsecond=0))
    access_for_url = access_date.replace(second=0, minute=0, hour=0)
    url = "https://api.covid19api.com/country/indonesia?from={}&to={}".format(
           access_for_url.isoformat() + 'Z',
           (access_for_url - timedelta(days=7)).isoformat() + 'Z')
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)
    json_list = json.loads(response.text.encode('utf8'))
    if len(json_list) > 1:
        dict_to_check = json_list[-1]
        temp = COVIDStat(date_accessed = access_date,
                         confirmed     = dict_to_check['Confirmed'],
                         deaths        = dict_to_check['Deaths'],
                         recovered     = dict_to_check['Recovered'],
                         active        = dict_to_check['Active'])
        access_db(temp)
    return JsonResponse(model_to_dict(COVIDStat.objects.latest('date_accessed')))
    
def access_db(temp):
    try:
        latest_change = tuple(temp.change(COVIDStat.objects.latest('date_accessed')).values())
        if latest_change != (0, 0, 0, 0):
            temp.save()
        else:
            del temp
    except COVIDStat.DoesNotExist:
        temp.save()

    

covid_count/templates/covid_count/index.html
{% extends 'base.html' %}
{% load static %}

{% block additional-styles %}
<link rel="stylesheet" href="{% static 'covid_count/styles.css' %}">
<link rel="stylesheet" href="{% static 'covid_count/index_styles.css' %}">
<title>EDUCOVID - Home</title>
{% endblock %}

{% block content %}
<div id = "page-wrapper container-fluid">
    <div id = "title-card" class = "card container my-3 text-center py-3 bold">
    <span id = "title"> 🦠 Selamat datang di EDUCOVID 😷 </span>
    </div>
    <div id = "description" class = "card container my-3 py-3">
    EDUCOVID merupakan website edukasi mengenai virus COVID-19 yang saat ini sedang mewabah di Indonesia dan hampir seluruh dunia. Website ini bertujuan untuk memberikan edukasi mengenai definisi, gejala, cara penularan, 
    dan cara pencegahan virus COVID-19. Selain itu, website ini juga memuat informasi seperti banyaknya kasus COVID-19 yang sedang terjadi sekarang ini serta lokasi pusat kesehatan sebagai rujukan jika dibutuhkan.
    </div>
    <div class = "card container my-3 py-3">
        <div id = "tally-board" class = "row">
           <div class ="col-md-3 text-center">
           <p class ="tally-sub">Terkonfirmasi</p>
           <p class ="tally-number danger">{{ confirmed }}</p>
           </div>
           
           <div class ="col-md-3 text-center">
           <p class ="tally-sub">Meninggal</p>
           <p class ="tally-number danger">{{ deaths }}</p>
           </div>
           
           <div class ="col-md-3 text-center">
           <p class ="tally-sub" id="recovered">Sembuh</p>
           <p class ="tally-number safe">{{ recovered }}</p>
           </div>
           
           <div class ="col-md-3 text-center">
           <p class ="tally-sub">Aktif</p>
           <p class ="tally-number danger">{{ active }}</p>
           </div>
        </div>
        <div class = "container text-center">
        <a id="an_url" href= "{% url 'covid_count:table' %}">
        Lihat data selengkapnya
        </a>
        </div>
    </div>
    <div id = "links" class = "container my-3">
        <div class = "row">
        <div id = "link-1" class = "card container col-md-4 py-3">
        <a href = "{% url 'edukasi:edukasi' %}">
        Edukasikan diri anda lebih lanjut mengenai COVID-19!
        </a>
        </div>
        <div id = "link-2" class = "card container col-md-4 py-3">
        <a href = "{% url 'rs_rujukan:index' %}">
        Lihat daftar rujukan RS berdasarkan provinsi anda!
        </a>
        </div>
        <div id = "link-3" class = "card container col-md-4 py-3">
        <a id="" href = "{% url 'screening_tests:test' %}">
        Isi kuesioner singkat mengenai  gejala COVID-19!
        </a>
        </div>
        </div>
    </div>
    <div id = "about" class = "card container my-3 py-3">
    <a id="an_url" href = "{% url 'aboutUs:aboutUs' %}">
    Lihat tim developer website ini!
    </a>
    </div>
    
</div>
{% endblock %}

covid_count/templates/covid_count/table.html
{% extends 'base.html' %}
{% load static %}

{% block additional-styles %}
<link rel="stylesheet" href="{% static 'covid_count/styles.css' %}">
<link rel="stylesheet" href="{% static 'covid_count/table_styles.css' %}">
<title>EDUCOVID - Data</title>
{% endblock %}

{% block content %}
<div id = "page-wrapper">
    <div id = "title-card" class = "card container text-center bold my-3 py-3">
    <span id = "title"> COVID-19 Track </span>
    </div>
    <div class = "container my-3 py-3">
    <table class = "table" id = "table">
        <thead id = "table-header">
            <th scope = "col" class = "table-column">
            Waktu
            </th>
            <th scope = "col" class = "table-column">
            Terkonfirmasi
            </th>
            <th scope = "col" class = "table-column">
            Meninggal
            </th>
            <th scope = "col" class = "table-column">
            Sembuh
            </th>
            <th scope = "col" class = "table-column">
            Aktif
            </th>
        </thead>
        <tbody>
        {% for entry in database %}
        <tr class = "table-row">
            <th scope = "row" class = "table-column">
            {{ entry.date_accessed }}
            </th>
            <td class = "table-column">
            {{ entry.confirmed }}
            </td>
            <td class = "table-column">
            {{ entry.deaths }}
            </td>
            <td class = "table-column">
            {{ entry.recovered }}
            </td>
            <td class = "table-column">
            {{ entry.active }}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}