Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
]

aboutUs/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'aboutUs'

urlpatterns = [
    path('', views.AboutUs, name='aboutUs'),
]

educovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
]

edukasi/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'edukasi'

urlpatterns = [
    path('', views.edukasi, name='edukasi'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('story1/', views.home2, name='home2'),
    path('story5/', views.home, name='home'),
    path('story5/cv/', views.cv, name='cv'),
]

rs_rujukan/urls.py
from django.contrib import admin
from django.urls import path
from rs_rujukan import views

app_name = "rs_rujukan"

urlpatterns = [
   	path('', views.index, name='index'),
]

screening_tests/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'screening_tests'

urlpatterns = [
    path('', views.test, name='test'),
    path('result/', views.result, name='res'),
]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block additional-styles %}
    {% endblock %}
</head>

<body>
    <div class="placeholder">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container" >
                <a class="navbar-brand" href="{% url 'covid_count:index' %}">
                    <img src="https://www.flaticon.com/svg/static/icons/svg/2813/2813238.svg">
                    <small class="font-weight-bold mb-0 text-uppercase">EDUCOVID</small>
                </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'covid_count:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'edukasi:edukasi' %}">Edukasi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'rs_rujukan:index' %}">RS Rujukan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'screening_tests:test' %}">Uji Screening</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'aboutUs:aboutUs' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
        
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-center">
            EDUCOVID
        </div>
        <div class="footer-copyright text-center py-3">
            ©2020 Kelompok D11, All Rights Reserved
        </div>
    </footer>
</body>
</html>